### ISSUE TITLE
How to Prune the node?

### ISSUE THREAD

**Issue by FarmerFans** [scroll-tech/go-ethereum#1020]
```sh
geth --datadir=./datadir snapshot prune-state
```

INFO [09-03|17:26:23.115] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-03|17:26:23.115] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [09-03|17:26:23.115] Disable transaction unindexing for archive node 
INFO [09-03|17:26:23.115] Set global gas cap                       cap=50,000,000
INFO [09-03|17:26:23.115] Allocated cache and file handles         database=/home/node/scroll/datadir/geth/chaindata cache=512.00MiB handles=262,144
INFO [09-03|17:26:24.832] Opened ancient database                  database=/home/node/scroll/datadir/geth/chaindata/ancient readonly=false
ERROR[09-03|17:26:24.840] Failed to open snapshot tree             err="missing or corrupted snapshot"
missing or corrupted snapshot

**Comment by Thegaram** [comment]
Pruning is currently not supported, we will add this in a future release.
