### ISSUE TITLE
backlog: remove mem trace 

### ISSUE THREAD

**Issue by lispc** [scroll-tech/go-ethereum#131]
after https://github.com/scroll-tech/common-rs/pull/32 is used,

we can set vm.LogConfig{EnableMemory: true} to false. i guess doing this can reduce blockResult size 5-10times.

(I remember maybe we have to change 2 place? One is for the realtime websocket , the other is getBlockResultByHash fetching/regerating for old block trace? )

**Comment by mask-pp** [comment]
Does that mean we can turning off Trace by params?

**Comment by mask-pp** [comment]
Or just don't load memory trace?

**Comment by icemelon** [comment]
@lispc I think #134 should be enough, right? we only need to disable the trace in the VM config. No need to change any API such as `getBlockResultByHash`.
