### ISSUE TITLE
problems of 'AccountCreated' in trace

### ISSUE THREAD

**Issue by lispc** [scroll-tech/go-ethereum#137]
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/2833376/182053993-e9ab51d7-b446-4be5-af0a-1b973db03f3c.png">

If we treat "accountCreated" be the state before the block/tx, shouldn't nonce be zero?

**Comment by noel2004** [comment]
After EIP158, nonce is 1 for every new created contract (so they would not be erased by considering as empty?)

Refer the code here:
https://github.com/scroll-tech/go-ethereum/blob/d421337df58074bdee8d8cb8fa592ece5a2300e8/core/vm/evm.go#L446
