### ISSUE TITLE
Problem with zktrie get

### ISSUE THREAD

**Issue by icemelon** [scroll-tech/go-ethereum#138]
After applying this [change](https://github.com/scroll-tech/go-ethereum/pull/136/commits/94d77bf3854439ad6f5c3cd4fe29b1868413a785), zktrie will run into the follow error.

```
INFO [08-02|18:36:04.135] 🔨 mined potential block                  number=7 hash=b4978e..cd3412
INFO [08-02|18:36:07.359] Submitted contract creation              hash=0xc494363fc06405b60fbcefd03257321aaa8cca90418e6edeb112805d7e691e2b from=0x4cb1aB63aF5D8931Ce09673EbD8ae2ce16fD6571 nonce=7 contract=0x48235a4b7D02F5874dc82F7419cbeaeb0043eF2f value=0
ERROR[08-02|18:36:10.138] Storage proof not available              error="storage trie for requested address does not exist" address=0x48235a4b7D02F5874dc82F7419cbeaeb0043eF2f key=0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc
ERROR[08-02|18:36:10.138] Storage proof not available              error="storage trie for requested address does not exist" address=0x48235a4b7D02F5874dc82F7419cbeaeb0043eF2f key=0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103
```

To reproduce this error, you just run the `run_deploy_contract.sh` script in the testnet repo. This error appeared in the first transaction that tries to deploy ERC20 gateway contract. But the second deployment transaction of the same contract succeeded afterward. I attached the error log from the deployment script here:
[deploy_tx_error.log](https://github.com/scroll-tech/go-ethereum/files/9247795/deploy_tx_error.log)

**Comment by hsyodyssey** [comment]
Have this issue fixed? Or Is there a PR in the works to solve this problem? I was just reading through the code and found what might be a problem.

**Comment by OrestTa** [comment]
FYI @Thegaram @HAOYUatHZ
