### ISSUE TITLE
Update go.mod and imports so that we can build remotely

### ISSUE THREAD

**Issue by jules** [scroll-tech/go-ethereum#14]

**Comment by mask-pp** [comment]
We'd better not change, keep original is easier upgrade and maintenance.

**Comment by jules** [comment]
@mask-pp it's a fair point, and I will make sure we use the standard geth for any imports we need in the sequencer. However, building the repo will currently use the standard geth imports, so any of the changes we make to the scroll version will not reflect on build time. We also run into errors when trying to fetch the scroll version of geth on the sequencer repo, because the go.mod paths are mismatched. I'll update the issue title

**Comment by mask-pp** [comment]
> @mask-pp it's a fair point, and I will make sure we use the standard geth for any imports we need in the sequencer. However, building the repo will currently use the standard geth imports, so any of the changes we make to the scroll version will not reflect on build time. We also run into errors when trying to fetch the scroll version of geth on the sequencer repo, because the go.mod paths are mismatched. I'll update the issue title

**Comment by mask-pp** [comment]
> > @mask-pp it's a fair point, and I will make sure we use the standard geth for any imports we need in the sequencer. However, building the repo will currently use the standard geth imports, so any of the changes we make to the scroll version will not reflect on build time. We also run into errors when trying to fetch the scroll version of geth on the sequencer repo, because the go.mod paths are mismatched. I'll update the issue title

Yes, we neeed to do that change.

**Comment by s7v7nislands** [comment]
@jules just curious, why not use replace command in go.mod?
