### ISSUE TITLE
trace seems incorrect

### ISSUE THREAD

**Issue by 0xmountaintop** [scroll-tech/go-ethereum#153]
there may be some issue with sync.pool?

block 7871
a uniswap tx reverted

![image](https://user-images.githubusercontent.com/37070449/188803462-583155b3-3da7-4dc4-9255-9b43fee66c22.png)
There should be an error “out of gas” but there isn't

trace:
https://scrollco.slack.com/files/U02PP3R89HB/F041MHR6WHE/7871.block_result.json

**Comment by 0xmountaintop** [comment]
+ https://l2scan.scroll.io/block/7871/transactions
+ https://l2scan.scroll.io/tx/0x632c51227c2635d2d0b06ba962523e9b4fbc7c8f52798ea5f417ff61f4e98f78

**Comment by mask-pp** [comment]
It's a common `ErrOutOfGas ` error, search  `"callFailed":true,`
