### ISSUE TITLE
doc: add a cmd example for run l2geth

### ISSUE THREAD

**Issue by lispc** [scroll-tech/go-ethereum#183]
Outside developers are trying to play with our geth fork while the current README lacks of some details to launch, for example, the options "--syncmode/--networkid/--gcmode archive/--trace.mptwitness" should be provided correctly.

Another option is to open source some our internal tools like integration-tests/testnet?

**Comment by OrestTa** [comment]
Agreed, same observation/requests. @icemelon WDYT?

**Comment by 0xmountaintop** [comment]
closed. can use github.com/scroll-tech/trace-dumper
