### ISSUE TITLE
this is a test bug - pls process :)

### ISSUE THREAD

**Issue by OrestTa** [scroll-tech/go-ethereum#191]
#### System information

Geth version: 1
OS & Version: ubuntu
Commit hash : aaabba

#### Expected behaviour

works

#### Actual behaviour

doesn't work

#### Steps to reproduce the behaviour

run ./geth

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rraulxavier** [comment]
@OrestTa Hi Orest, thanks for the report, we are working on it and will be back to you shortly. 

CC: https://app.asana.com/0/1202293017617135/1203522391730117

**Comment by OrestTa** [comment]
Sure, I'll be a patient bug reporter :)

**Comment by rraulxavier** [comment]
Hi Orest, the bug fix was implemented and deployed to main. Please let us know if you encounter any other issues.
