### ISSUE TITLE
Potential OOM risk due to excessive local transactions

### ISSUE THREAD

**Issue by hsyodyssey** [scroll-tech/go-ethereum#264]
I am working on making some stress tests, (ignore this if you have done similar tests).

- All raw transactions sent via the sequencer’s RPC will be considered local transactions, which will not be discarded or evicted by the transaction pool, even if the pool size is extremely large.
- Considering the hot scenario when the main net is online, a large number of local transactions may cause the transaction pool to be too large and take up too much memory, eventually causing OOM.
- I downloaded the code from the develop branch and ran it on Ubuntu 22. With a little tool for stress testing, it ended up causing the OOM.
- A worse problem is that after a restart, these unprocessed local transactions are reloaded into the transaction pool. So if there are still a lot of newly added transactions coming in via RPC at this moment, this is likely to cause a second crash.
- In the original geth, besides not so many transactions, more transactions are Remote Transactions transferred via P2P, and they are easily discarded to avoid oversizing the transaction pool.

p.s. It is difficult to reproduce this problem on Mac because of MacOS‘s ‘excellent’ Swap mechanism.

In addition to increasing the performance of the machine, perhaps consider adding an additional limit on local transactions to avoid extreme cases.

**Comment by Thegaram** [comment]
> All raw transactions sent via the sequencer’s RPC will be considered local transactions

Hi @hsyodyssey, thanks for your help testing the node. Can you provide some proof for this claim? I believe only transactions from the local accounts (as defined by the node config) will be considered local.

**Comment by hsyodyssey** [comment]
Hi, it seems that the criteria for determining whether a transaction is local or not is not just the local Account. You can look at the [SendTx](https://github.com/scroll-tech/go-ethereum/blob/develop/eth/api_backend.go#L242-L245) function in ethapi. According to the call chain of the function(SendTx), all transactions that are passed through SendTx are marked local.

In our test, except for the original transaction(send testeth to testaccounts), the originator of the rest of the transactions are not in the node config, they are randomly generated foundry-Anvil.

**Comment by hsyodyssey** [comment]
I'm thinking about how to send the proof to you guys. I can record a video or something.

**Comment by Thegaram** [comment]
This is the entry point for user-submitted transactions: https://github.com/scroll-tech/go-ethereum/blob/develop/internal/ethapi/api.go#L1801

**Comment by hsyodyssey** [comment]
ok, it would be great if it is not a problem.  I have run a node locally and then used an additional client, requesting the local node RPC in the following way.  If this type of request is not allowed, there is no problem.

```
client, err := ethclient.Dial(ChainHttpAddress)
client.SendTransaction(context.Background(), signedTx)
```

**Comment by hsyodyssey** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/47173566/230804949-8174e4ed-a02a-4cd7-8d13-3ca837d7e7f4.png">

I used the same client code and successfully made a transfer on Alpha l2 from 0x6a300ACf4005879C311A435a8486538e43a32D99.  If the L2 Sequencer now use another enrty function to handle raw transactions that's fine. On my local node, it calls SendTx.

**Comment by hsyodyssey** [comment]
I checked the codebase. The function call chain is: SubmitTransaction -> [SubmitTransaction](https://github.com/scroll-tech/go-ethereum/blob/develop/internal/ethapi/api.go#L1731-L1733) ->  [SendTx](https://github.com/scroll-tech/go-ethereum/blob/develop/internal/ethapi/backend.go#L76) -> [impl](https://github.com/scroll-tech/go-ethereum/blob/develop/eth/api_backend.go#L242-L245)

**Comment by Thegaram** [comment]
Yes, you're right, txs submitted through RPC (`eth_sendRawTransaction`) will be treated as local. This behaviour is inherited from geth.

I believe this won't cause any problems though, our sequencer does not accepts txs through RPC, only through the p2p protocol.

**Comment by hsyodyssey** [comment]
> Yes, you're right, txs submitted through RPC (`eth_sendRawTransaction`) will be treated as local. This behaviour is inherited from geth.
> 
> I believe this won't cause any problems though, our sequencer does not accepts txs through RPC, only through the p2p protocol.

Great! This should not be an issue for the Sequencer node's availability.
