### ISSUE TITLE
high memory usage while use API debug_*

### ISSUE THREAD

**Issue by shu-unifra** [scroll-tech/go-ethereum#268]
When continuously calling the API `debug_traceBlockByNumber`, the memory occupied by Geth keeps increasing until it runs out of memory (16GB).
The possible reason is that `runtime.SetFinalizer` depends on the garbage collector (GC) to reclaim objects, and the object pool grows faster than the GC can reclaim.

_core/vm/logger.go:NewStructlog_
```
func NewStructlog(pc uint64, op OpCode, gas, cost uint64, depth int, err error) *StructLog {
    structlog := loggerPool.Get().(*StructLog)
    structlog.Pc, structlog.Op, structlog.Gas, structlog.GasCost, structlog.Depth, structlog.Err = pc, op, gas, cost, depth, err

    runtime.SetFinalizer(structlog, func(logger *StructLog) {
        logger.clean()
        loggerPool.Put(logger)
    })
    return structlog
}
```
_core/types/l2trace.go:NewStructLogResBasic_
```
func NewStructLogResBasic(pc uint64, op string, gas, gasCost uint64, depth int, refundCounter uint64, err error) *StructLogRes {
	logRes := loggerResPool.Get().(*StructLogRes)
	logRes.Pc, logRes.Op, logRes.Gas, logRes.GasCost, logRes.Depth, logRes.RefundCounter = pc, op, gas, gasCost, depth, refundCounter
	if err != nil {
		logRes.Error = err.Error()
	}
	runtime.SetFinalizer(logRes, func(logRes *StructLogRes) {
		logRes.Stack = logRes.Stack[:0]
		logRes.Memory = logRes.Memory[:0]
		logRes.Storage = nil
		logRes.ExtraData = nil
		logRes.Error = ""
		loggerResPool.Put(logRes)
	})
	return logRes
}
```
When adding runtime.GC in the function `traceBlock` (https://github.com/scroll-tech/go-ethereum/blob/develop/eth/tracers/api.go#L568), it seems that the problem of excessive memory usage no longer occurs. 
Is there a more elegant solution?

**Comment by georgehao** [comment]
Hi, Get it. It seem like there have a memory leak, I will try to resolve it. You can use the runtime.GC as a temporary solution.

**Comment by mask-pp** [comment]
This API is cumbersome, maybe it's not suitable to call it continuously.

**Comment by shu-unifra** [comment]
> This API is cumbersome, maybe it's not suitable to call it continuously.

But we need this, haha~

**Comment by georgehao** [comment]
this bug has fixed. use the latest version.
