### ISSUE TITLE
transaction pending forever

### ISSUE THREAD

**Issue by xx5ll** [scroll-tech/go-ethereum#549]
#### System information

Geth version: `5.0.0-mainnet`
OS & Version: Ubuntu 22.04
Commit hash : cfd9de0f92452af879503ff0aa4eb623989be0dd

#### Expected behaviour
send a transaction, and pending for a while, then mined by sequencer

#### Actual behaviour
pending forever, even the gas price is higher than normal. but i can cancel the transaction with metamask manually.

#### Steps to reproduce the behaviour
i'm running a scroll node on my server. and then i send the tx through rpc.

```golang
innerData := &types.LegacyTx{
	Nonce:    nonce,
	To:       &manager.Spender,
	Value:    value,
	Gas:      uint64(gas),
	GasPrice: gasPrice,
	Data: tx.Input,
}
rawTx := types.NewTx(innerData)
sig, err := crypto.Sign(account.Signer.Hash(rawTx).Bytes(), pk)
if err != nil {
	log.Info("sign err", "err", err)
}
newTx, err := rawTx.WithSignature(account.Signer, sig)
ethClient.SendTransaction(ctx, newTx)
```
and my wallet has pended hundreds of transactions in scroll network. i also try to replace the transaction with 2 gwei gas price, but still pending. i have to cancel the transaction with metamask.

**Comment by Thegaram** [comment]
Thank you for reporting this. We confirmed that the transaction was dropped, investigating the root cause.

Would it be possible to share the source code of the target contract `0x9ca78b2ec99ff2fd33eb455247b10bfb5d816dc7`?

**Comment by WonderfulFull** [comment]
i can not share the source code because it's classified, but it have selfdestruct in the code.

**Comment by xx5ll** [comment]
> Thank you for reporting this. We confirmed that the transaction was dropped, investigating the root cause.
> 
> Would it be possible to share the source code of the target contract `0x9ca78b2ec99ff2fd33eb455247b10bfb5d816dc7`?

i can not share the source code because it's classified, but it have selfdestruct in the code. should i remove that and deploy again?

**Comment by Thegaram** [comment]
`SELFDESTRUCT` during a transaction's execution will cause it to revert, but it will not cause it to be pending indefinitely.

Does your contract make multiple calls to `keccak` or to any precompiles? If yes, it would be useful to know which of these are called and approximately how many times.

**Comment by xx5ll** [comment]
> `SELFDESTRUCT` during a transaction's execution will cause it to revert, but it will not cause it to be pending indefinitely.
> 
> Does your contract make multiple calls to `keccak` or to any precompiles? If yes, it would be useful to know which of these are called and approximately how many times.

nope. but there is many try catch...

**Comment by Thegaram** [comment]
The transaction was dropped because the sequencer estimated that it cannot be proven using our current proving system. This is expected behaviour. We'll try to provide more details as to why that is the case, but it might be challenging to find the root cause without knowing the contract's internal logic.

**Comment by xx5ll** [comment]
> The transaction was dropped because the sequencer estimated that it cannot be proven using our current proving system. This is expected behaviour. We'll try to provide more details as to why that is the case, but it might be challenging to find the root cause without knowing the contract's internal logic.

i can send you the code privately. please give me some email, telegram or something.

**Comment by Thegaram** [comment]
Thanks. You can find my email in the commit history (`git log`).
