### ISSUE TITLE
Synchronization stuck at 4096173

### ISSUE THREAD

**Issue by letsbangout** [scroll-tech/go-ethereum#671]
I have several scroll mainnet nodes which have all stopped synchronizing.  They run a combination of 5.0.0 and 5.1.10.  One node in particular I have tried upgrading to 5.1.22, but it still does not synchronize.

#### System information

Geth version: `5.1.22-mainnet`
OS & Version: Ubuntu 20.04

#### Expected behaviour

Normal synchronization

#### Actual behaviour

WARN [03-14|23:03:38.902] Rewinding blockchain                     target=4,096,000
WARN [03-14|23:03:38.994] Head headers broke chain ordering        peer=e6eb0f66 index=0 requested=4,096,167 received=4,135,098
WARN [03-14|23:03:38.994] Synchronisation failed, dropping peer    peer=e6eb0f662a7315bba4c25af524ee2314f846a76b12aa3628f51d7f31488bae8f err="retrieved hash chain is invalid: head headers broke chain ordering"
WARN [03-14|23:03:38.994] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [03-14|23:03:38.995] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [03-14|23:03:39.028] Loaded most recent local header          number=4,096,000 hash=077f6c..e13c65 td=8,192,001 age=1d9h3m
INFO [03-14|23:03:39.028] Loaded most recent local full block      number=4,096,000 hash=077f6c..e13c65 td=8,192,001 age=1d9h3m
INFO [03-14|23:03:39.028] Loaded most recent local fast block      number=4,096,000 hash=077f6c..e13c65 td=8,192,001 age=1d9h3m
INFO [03-14|23:03:40.095] Finished upgrading chain index           type=bloombits
INFO [03-14|23:03:41.654] Downloader queue stats                   receiptTasks=0 blockTasks=1839 itemSize=1.33KiB throttle=8192
INFO [03-14|23:03:42.991] Imported new chain segment               blocks=5 txs=31 mgas=3.684 elapsed=1.336s mgasps=2.756 number=4,096,005 hash=2c68b7..349472 age=1d9h3m   dirty=0.00B
INFO [03-14|23:03:51.023] Imported new chain segment               blocks=37 txs=227 mgas=27.718 elapsed=8.012s mgasps=3.459 number=4,096,042 hash=90d9fb..d8782e age=1d9h1m   dirty=0.00B
INFO [03-14|23:03:59.034] Imported new chain segment               blocks=41 txs=244 mgas=28.984 elapsed=8.011s mgasps=3.618 number=4,096,083 hash=20901d..2c33f2 age=1d9h     dirty=0.00B
INFO [03-14|23:04:07.117] Imported new chain segment               blocks=36 txs=255 mgas=29.677 elapsed=8.083s mgasps=3.672 number=4,096,119 hash=6fd6f8..e5da40 age=1d8h58m  dirty=0.00B
INFO [03-14|23:04:15.168] Imported new chain segment               blocks=40 txs=248 mgas=30.268 elapsed=8.051s mgasps=3.759 number=4,096,159 hash=133260..b28657 age=1d8h56m  dirty=0.00B
WARN [03-14|23:04:17.595] Synchronisation failed, dropping peer    peer=c915787af8f364ef20be8422df0370835119d9737f7225111fcb9540b16925e2 err="retrieved hash chain is invalid: unknown L1 message data"
WARN [03-14|23:04:17.595] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [03-14|23:04:17.595] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
ERROR[03-14|23:04:23.251]
########## BAD BLOCK #########
Chain config: {ChainID: 534352 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, Berlin: 0, London: 0, Arrow Glacier: <nil>, Archimedes: 0, Shanghai: 0, Banach: <nil>, Engine: clique, Scroll config: {useZktrie: true, maxTxPerBlock: 100, MaxTxPayloadBytesPerBlock: 122880, feeVaultAddress: 0x5300000000000000000000000000000000000005, l1Config: {l1ChainId: 1, l1MessageQueueAddress: 0x0d7E906BD9cAFa154b048cFa766Cc1E54E39AF9B, numL1MessagesPerBlock: 10, ScrollChainAddress: 0xa13BAF47339d63B743e7Da8741db5456DAc1E556}}}

Number: 4096302
Hash: 0x481212a33900cb0baf391efab8c45a55769b60b78ec0db60ec47a28e150f5b56
ParentHash: 0x92b2dfdb7c25b0851d904c5aae72130228148c841d0125ca7254dbf8633b574a

Error: unknown ancestor
##############################

ERROR[03-14|23:04:23.253]
########## BAD BLOCK #########
Chain config: {ChainID: 534352 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, Berlin: 0, London: 0, Arrow Glacier: <nil>, Archimedes: 0, Shanghai: 0, Banach: <nil>, Engine: clique, Scroll config: {useZktrie: true, maxTxPerBlock: 100, MaxTxPayloadBytesPerBlock: 122880, feeVaultAddress: 0x5300000000000000000000000000000000000005, l1Config: {l1ChainId: 1, l1MessageQueueAddress: 0x0d7E906BD9cAFa154b048cFa766Cc1E54E39AF9B, numL1MessagesPerBlock: 10, ScrollChainAddress: 0xa13BAF47339d63B743e7Da8741db5456DAc1E556}}}

Number: 4096303
Hash: 0x2117cf362d45fd8972638b2f7ef461b60d9b8fa8119a97ec2b7d3d12d22ef07a
ParentHash: 0x481212a33900cb0baf391efab8c45a55769b60b78ec0db60ec47a28e150f5b56

Error: unknown ancestor
##############################

#### Steps to reproduce the behaviour

Compile 5.1.22 from source
./l2geth-source/build/bin/geth attach http://127.0.0.1:8545
debug.setHead("0x3E8000")
#4096000

**Comment by 0xmountaintop** [comment]
how do you run your geth? what docs do you follow?

**Comment by letsbangout** [comment]
Actually this looks like L1 is not synchronized.  Perhaps a more intuitive error message could be given?  Closing.
