### ISSUE TITLE
docs: update link in go-ethereum/accounts/abi /abi.go

### ISSUE THREAD

**Issue by alexanderblv** [scroll-tech/go-ethereum#686]
https://github.com/scroll-tech/go-ethereum/blob/06f4573e49af9d6df0ecfa218b6e8684ccf36da1/accounts/abi/abi.go#L171
Line 171, the data is outdated. A big update has been released. Here is a new link:
https://docs.soliditylang.org/en/v0.8.25/contracts.html#fallback-function

For some reason I can't create a Pull Request and because of this I have to create Issue

**Comment by 0xmountaintop** [comment]
after we sync with https://github.com/ethereum/go-ethereum upstream we don't need to update ourselves.

**Comment by alexanderblv** [comment]
I understand you, but if you update the code according to my comment, it would be better.
