### ISSUE TITLE
Meta issue on trace

### ISSUE THREAD

**Issue by lispc** [scroll-tech/go-ethereum#69]
1. executionResults.Sender.Nonces in are not correct?  They are fetched **after** the whole block execution 
   <https://github.com/scroll-tech/go-ethereum/blob/40e8f088b6adb8dcdc050759d978d19d18327a77/core/blockchain.go#L1376-L1381>

**Comment by 0xmountaintop** [comment]
Yeah I've noticed that and am making a list.

1. nonce fetch incorrect
2. balance seems weird?
3. why coinbase's address &  code_hash are 0？

---

For refecence, sample trace: https://gist.github.com/HAOYUatHZ/41a9994000b1ff2452100468f29f8881

**Comment by mask-pp** [comment]
> Yeah I've noticed that and am making a list.
> 
> 1. nonce fetch incorrect
> 2. balance seems weird?
> 3. why coinbase's address &  code_hash are 0？
> 
> For refecence, sample trace: https://gist.github.com/HAOYUatHZ/41a9994000b1ff2452100468f29f8881

The reason is we fetched data before opcode executed, so it's normal that the data is not right.

**Comment by mask-pp** [comment]
> 1. executionResults.Sender.Nonces in are not correct?  They are fetched **after** the whole block execution
>    https://github.com/scroll-tech/go-ethereum/blob/40e8f088b6adb8dcdc050759d978d19d18327a77/core/blockchain.go#L1376-L1381
