### ISSUE TITLE
What is the difference between v5.1.33 and scroll-v5.1.33?

### ISSUE THREAD

**Issue by qezz** [scroll-tech/go-ethereum#696]
I can see a new type of tags now exists.

Previously it was more or less always `scroll-vX.Y.Z`, and now it's both. 
There's also a problem that the `v5.1.33` and `scroll-v5.1.33` do point to different commits:
- `v5.1.33` - 5a34f0651e69361704fb8a04447f8d7689323e5b
- `scroll-v5.1.33` - 4c2b5671165346a8dea1d10e686a62c6c66c4d0e

Why is it done this way?
What should be built and used in prod?

**Comment by georgehao** [comment]
v5.1.33 built wrong, have deleted
