### ISSUE TITLE
how to get the safe height of the blockchain

### ISSUE THREAD

**Issue by liyue201** [scroll-tech/go-ethereum#716]
i want to  get the safe height， but it returns null

```
curl --location --request POST 'https://scroll.drpc.org' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_getBlockByNumber",
	"params":["safe", false],
	"id":1
}'
```

```
{"id":1,"jsonrpc":"2.0","result":null}
```

**Comment by Thegaram** [comment]
The `"safe"` parameter is not supported on Scroll.

Some RPC providers suppport the `"finalized"` tag (or you can enable it on your own node). See "rollup verification" [here](https://github.com/scroll-tech/go-ethereum/releases/tag/scroll-v5.1.10) for more details.
