### ISSUE TITLE
eth_call return error

### ISSUE THREAD

**Issue by cherry-yl-sh** [scroll-tech/go-ethereum#728]
#### System information

Geth version: `geth version`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
a eth_call request for simulate
in ethereum or other op chain like optimism , arb, it work can return data
but in scroll not working
{
"jsonrpc": "2.0",
"method": "eth_call",
"params": [
{
"from": "0x0000000000000000000000000000000000000000",
"to": "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
"data": "0xd6383f940000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004e0000000000000000000000000ffdb071c2b58ccc10ad386f9bb4e8d3d664ce73c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000054fa000000000000000000000000000000000000000000000000000000000005fa35000000000000000000000000000000000000000000000000000000000000ae64000000000000000000000000000000000000000000000000000000005968606e0000000000000000000000000000000000000000000000000000000059682f000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000589406cc6185a346906296840746125a0e449764545fbfb9cf000000000000000000000000b6bcf9517d193f551d0e3d6860103972dd13de7b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e4b61d27f60000000000000000000000001c7d4b196cb0c7b01d743fbc6116a902379c7238000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000000000000000325602a77416a16136fdafd04b299fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d50fa9ee28202f8602e9a4c99af799c75c29afbc89000000000000000000000000000000000000000000000000000000006c7bacd00000000000000000000000000000000000000000000000000000000065ed35500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030834e50943434af33947ba6de358766961c7b89ae4b496a11d2b53771479e45220a8caa0024b81a2ed649b26a292c5f5b2870da090e3cc4490688a4874869721c00000000000000000000000000000000000000000000000000000000000000000000000000000000000041aa846693598194980f3bf50486be854704534c1622d0c2ee895a5a1ebe1508221909a27cc7971d9f522c8df13b9d8a6ee446d09ea7635f31c59d77d35d1281421c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
},
"latest"
],
"id": 1
}
here is the request
request to Ethereum. sepolia
![image](https://github.com/scroll-tech/go-ethereum/assets/60910788/27907ad1-812d-4884-9f8c-2548f170eefc)

#### Actual behaviour

but call. scroll sepolia return errror
image
![image](https://github.com/scroll-tech/go-ethereum/assets/60910788/83a27eae-e81f-4981-8adf-4c35bb2c3249)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Thegaram** [comment]
Thanks for submitting this issue. I was able to reproduce it on Scroll Sepolia.

While this is probably not the root cause, one thing I noticed is that in your `UserOp` `maxFeePerGas != maxPriorityFeePerGas` (`1500012654` and `1500000000` respectively). This will result in `"invalid opcode: BASEFEE"`, since Scroll currently does not support `block.basefee`. So I recommend setting these two to the same value.

https://github.com/eth-infinitism/account-abstraction/blob/2b1aac46a8b532121dab4af739bcb019f8693ae1/contracts/core/EntryPoint.sol#L763-L767

Can you tell us a bit more about the contracts and operations here? Is this an ERC20 approval operation from a smart account?

**Comment by cherry-yl-sh** [comment]
I am dev of AA paymaster, wanna supoort Scroll chain paymaster, 
in paymaster Relay  neet to call entrypoint address  simulateUserop Function to make sure  the data what paymaster generate is work, the issue i commit is form  use eth_call to call simulateUserop 
https://github.com/eth-infinitism/account-abstraction/blob/releases/v0.6/contracts/core/EntryPoint.sol#L184

**Comment by cherry-yl-sh** [comment]
I change maxFeePerGas And maxPriorityFeePerGas to the same value and i works!, thanks for support!!!

**Comment by cherry-yl-sh** [comment]
btw , how you get the    "invalid opcode: BASEFEE" this  information? are there any tools support scroll  debug ,I wanna get more debug  information ,so that i can try slove by myself first ~

**Comment by Thegaram** [comment]
> I change maxFeePerGas And maxPriorityFeePerGas to the same value and i works!

Glad to hear! I'm not sure the root cause is solved yet though, so please let us know if this issue happens again. If you're comfortable sharing the code of your `Paymaster` contract (`0x0Fa9ee28202F8602E9a4C99Af799C75C29AFbC89`), we can check if it has anything that would trigger this.

> btw , how you get the "invalid opcode: BASEFEE" this information?

I used Foundry to see what the expected execution would look like (it simulates it in a local VM):

```shell
> cast call --rpc-url "https://sepolia-rpc.scroll.io" 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 "simulateHandleOp((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes),address,bytes)" "(0xFfDB071C2b58CCC10Ad386f9Bb4E8d3d664CE73c,0,0x9406cc6185a346906296840746125a0e449764545fbfb9cf000000000000000000000000b6bcf9517d193f551d0e3d6860103972dd13de7b0000000000000000000000000000000000000000000000000000000000000000,0xb61d27f60000000000000000000000001c7d4b196cb0c7b01d743fbc6116a902379c7238000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000000000000000325602a77416a16136fdafd04b299fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000,21754,391733,44644,1500012654,1500000000,0x0fa9ee28202f8602e9a4c99af799c75c29afbc89000000000000000000000000000000000000000000000000000000006c7bacd00000000000000000000000000000000000000000000000000000000065ed35500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030834e50943434af33947ba6de358766961c7b89ae4b496a11d2b53771479e45220a8caa0024b81a2ed649b26a292c5f5b2870da090e3cc4490688a4874869721c,0xaa846693598194980f3bf50486be854704534c1622d0c2ee895a5a1ebe1508221909a27cc7971d9f522c8df13b9d8a6ee446d09ea7635f31c59d77d35d1281421c)" "0x0000000000000000000000000000000000000000" "0x" --trace
```

Then I manually replayed some internal calls (using `eth_call`).

**Comment by cherry-yl-sh** [comment]
the code of 0x0Fa9ee28202F8602E9a4C99Af799C75C29AFbC89
https://github.com/AAStarCommunity/basic_paymaster_contract/blob/main/contracts/VerifyingPaymaster.sol
the  issue about  simulates is fix , may can be close , thanks for supoort again!!!
