### ISSUE TITLE
Critical - Scroll stops syncing

### ISSUE THREAD

**Issue by CRossel87a** [scroll-tech/go-ethereum#732]
Hi,

I am using the most recent version of the scroll release. This morning the node stopped fetching blocks from sequencer/peers. Did the team turn on some firewall?

**Comment by Thegaram** [comment]
Are you running `scroll-v5.3.0`? Do you run it with the `--scroll` flag? What is the most recent block that your node has?

Can you check the value of `bernoulliBlock` in the startup logs of your node?

**Comment by CRossel87a** [comment]
Hi,

Happy to report it was as simple fix as adding the --scroll flag. I have been running the node for a while with no issue without it. Strange!

Thanks for the rapid response!
