### ISSUE TITLE
Bug with --scroll flag in latest version of docker image

### ISSUE THREAD

**Issue by zeroonesymphony** [scroll-tech/go-ethereum#810]
#### System information

Geth version: scroll-v5.3.41
OS & Version: Linux Ubuntu 22.04

#### Expected behaviour
The --scroll flag should function correctly in the latest version of scrolltech/l2geth.

#### Actual behaviour
The --scroll flag does not work as expected in the latest version of scrolltech/l2geth.
Exact error: 'flag provided but not defined: -scroll'

#### Steps to reproduce the behaviour
Try to run the node with the latest version of scrolltech/l2geth docker image.
command:
$ docker run --rm --name l2geth-docker -v $(pwd):/volume -p 8545:8545 -e RUST_LOG="info" -e CHAIN_ID="534352" scrolltech/l2geth:latest \
    --scroll \
    --datadir "/volume/l2geth-datadir" \
    --gcmode archive --cache.noprefetch \
    --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3,debug,scroll" \
    --l1.endpoint "$L2GETH_L1_ENDPOINT" --rollup.verify

#### Solution
I have fixed the issue by simply using the one version before the latest image which is [scroll-v5.3.37]

#### Backtrace

````
Check logs.txt
[logs.txt](https://github.com/user-attachments/files/15743112/logs.txt)

````

When submitting logs: please submit them as text and not screenshots.

**Comment by Thegaram** [comment]
Thanks for reporting this. It seems the `latest` version is not actively pushed currently. As a workaround please use a specific version for now, e.g. `scrolltech/l2geth:scroll-v5.3.41`.

**Comment by zeroonesymphony** [comment]
Sure, thanks.
