### ISSUE TITLE
`make nccc_geth` now attempts to install the binary into the system, and eventually tries to use `sudo`

### ISSUE THREAD

**Issue by qezz** [scroll-tech/go-ethereum#812]
It has been changed recently, and broke our CI for scroll

The build command

```
        build_cmd: |
          make nccc_geth && cp ./build/bin/geth /go/bin
```

The result (apparently since 5.3.29)

```
  > [build  9/15] RUN make nccc_geth && cp ./build/bin/geth /go/bin:
0.267 make: sudo: No such file or directory
0.267 make: *** [Makefile:17: libzstd] Error 127
```

https://github.com/scroll-tech/go-ethereum/blame/develop/Makefile
<img width="622" alt="image" src="https://github.com/scroll-tech/go-ethereum/assets/5172876/7cd22b0b-4cc1-4c80-b1df-c5cd406974ca">

Why was this done?
@colinlyguo by any chance do you have context on this decision?

**Comment by colinlyguo** [comment]
Hi, this issue is resolved in this PR: https://github.com/scroll-tech/go-ethereum/commit/e162fbb7c0e455305319e45832e76765f5badf3f

[v5.3.41](https://github.com/scroll-tech/go-ethereum/tree/scroll-v5.3.41) could be an alternative.

**Comment by qezz** [comment]
`5.3.41` seems to build fine. Skipping everything from 5.3.29 to <5.3.41.
