### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by mask-pp** [scroll-tech/go-ethereum#99]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour
ERROR[05-18|10:24:05.075] Transaction not found                    number=170 hash=04ffca..2f0a50 txhash=83ae4c..985800

#### Backtrace
This happens occasionally when debugging with Goland
````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 0xmountaintop** [comment]
what's this issue for? should we close this now?
